module.exports = {
    options: {
        colour_one: '#ff0000',
        colour_two: '#ffd4d4',
        colour_three: '#FFE3E2',
        table_colour: 'ghostwhite',
        heading: `Paul's Arsenal Collection`,
        sub_heading: `Programmes, tickets and memorabilia`,
        img_one_src: 'everton_prog_1.jpg',
        img_two_src: 'everton_prog_2.jpg',
        img_three_src: 'PM_home_prog2.jpg',
        team: 'Arsenal',
        intro: `<p class="section">Welcome to this site, which lists the programmes, tickets and other matchday Arsenal memorabilia in my collection and also highlights some of the gaps. If you can help with any item that I'm missing please email me at <a href='mailto:paul.matz@hotmail.com'>paul.axxxx@abc.com</a> or give me a call on 07xxxxxxxxxxx.  I also collect just about anything and everything related to Arsenal Football Club in addition to the matchday items shown here.</p> <p class="section">I am part of the team behind 'The Arsenal Collection' website, which  is a digital collection of Arsenal memorabilia. Already on this site are images from hundreds of programmes from my collection, showing every page of each programme, not just the front cover. One of my oldest programmes can be found <a href="http://thearsenalcollection.org.uk/sheffield-united-v-arsenal-football-league-division-one-wednesday-december-28th-1904/" target="_blank">here</a> and a pre-war handbook is <a href="http://thearsenalcollection.org.uk/1994-95-arsenal-handbook-2/" target="_blank">here</a>. Enjoy!.</p>`,
        data_points: {
            season: 'Season',
            date: 'Date',
            competition: 'Competition',
            opponent: 'Opponent',
            home_away: 'Home/Away',
            programme_got_want: 'Programme Got/Want',
            id: 'ID',
            friendly: 'Friendly',
            score: 'Score',
            cup_round: 'Cup Round',
            match_notes: 'Match Notes',
            ticket_got_want: 'Ticket Got/Want',
            programme_notes: 'Programme Notes',
            other_items: 'Other Items',
            non_first_team: 'Non First Team',
            is_ticket_collection: true,
            includes_non_first_team: true
        },
    },
    password: 'password',
    sheet_id: process.env.sheet_id,
    type: process.env.type,
    project_id: process.env.project_id,
    private_key_id: process.env.private_key_id,
    private_key: process.env.private_key,
    client_email: process.env.client_email,
    client_id: process.env.client_id,
    auth_uri: process.env.auth_uri,
    token_uri: process.env.token_uri,
    auth_provider_x509_cert_url: process.env.auth_provider_x509_cert_url,
    client_x509_cert_url: process.env.client_x509_cert_url
}
